# Generated by Django 3.1.3 on 2021-02-27 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '__first__'),
        ('teacher', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lesson_code', models.IntegerField()),
                ('lesson_credit', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('lesson', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson')),
                ('student', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('teacher', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='LessonNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_publish_date', models.DateField()),
                ('note_title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='')),
                ('file_description', models.CharField(max_length=255)),
                ('file_uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lesson_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='member_student',
            field=models.ManyToManyField(through='lesson.Membership', to='student.Student'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='member_teacher',
            field=models.ManyToManyField(through='lesson.Membership', to='teacher.Teacher'),
        ),
    ]
