# Generated by Django 3.1.3 on 2021-04-12 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '__first__'),
        ('student', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lesson_code', models.IntegerField()),
                ('lesson_credit', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LessonNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_publish_date', models.DateField()),
                ('note_title', models.CharField(max_length=255)),
                ('note_description', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('file_description', models.CharField(blank=True, max_length=255, null=True)),
                ('file_uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('exam1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exam2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lesson', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson')),
                ('student', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('teacher', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
            options={
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
