# Generated by Django 3.1.3 on 2021-02-28 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('student', 'lesson')},
        ),
    ]
