# Generated by Django 3.1.3 on 2021-02-28 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
        ('lesson', '0002_auto_20210228_2101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Membership',
            new_name='Enrollment',
        ),
    ]
