# Generated by Django 3.1.3 on 2021-03-07 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_auto_20210307_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='member_student',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='member_teacher',
        ),
    ]
