# Generated by Django 3.1.3 on 2021-03-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_auto_20210307_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonnotes',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lessonnotes',
            name='file_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lessonnotes',
            name='file_uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
