# Generated by Django 3.1.3 on 2021-03-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0007_lessonnotes_note_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonnotes',
            old_name='lesson_code',
            new_name='lesson_id',
        ),
    ]
