# Generated by Django 3.1.3 on 2021-03-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('student', '0001_initial'),
        ('lesson', '0008_auto_20210307_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='student',
            field=models.ManyToManyField(through='lesson.Enrollment', to='student.Student'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ManyToManyField(through='lesson.Enrollment', to='teacher.Teacher'),
        ),
    ]
