# Generated by Django 3.1.3 on 2021-03-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0009_auto_20210309_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonnotes',
            old_name='lesson_id',
            new_name='lesson',
        ),
    ]
