# Generated by Django 3.1.3 on 2021-03-09 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0010_auto_20210309_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='student',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
    ]
