# Generated by Django 3.1.3 on 2021-06-14 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_auto_20210423_0338'),
        ('meet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='meet_link',
        ),
        migrations.AddField(
            model_name='meet',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson'),
            preserve_default=False,
        ),
    ]
